#ifndef ERROR_H_INCLUDED
#define ERROR_H_INCLUDED

typedef enum {
    RC_OK = 0,
    RC_EXIT = 1,
    RC_PIPE_CREATION_ERROR = -100,
    RC_FORK_FAILED = -101,
    RC_ERROR_SENDING_TO_SERVER = -102,
    RC_ERROR_RECEIVING_FROM_SERVER = -103,
    RC_ERROR_SENDING_TO_CLIENT = -104,
    RC_ERROR_RECEIVING_FROM_CLIENT = -105,
    RC_BROKEN_INPUT_CHANNEL_FROM_CLIENT = -106,
    RC_BROKEN_INPUT_CHANNEL_FROM_SERVER = -107,
    RC_CLIENT_SENT_INCOMPLETE_HEADER = -108,
    RC_SERVER_SENT_INCOMPLETE_HEADER = -109,
    RC_MISSING_MESSAGE_SEPARATOR = -110,
    RC_SERVER_CLOSED_PIPE = -111,
    RC_SELECT_ERROR = -150,
    // Options handling
    RC_UNKNOWN_OPTION = -200,
    RC_NO_MODE_SELECTED = -201
} ResultCode;

#endif
